//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/com.itisnotonlyme.manejo-de-inputs/Sample/Demo/_Scripts/Inputs/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""Personaje"",
            ""id"": ""184de408-7b25-4194-9be9-c8f6884c3c88"",
            ""actions"": [
                {
                    ""name"": ""Movimiento"",
                    ""type"": ""PassThrough"",
                    ""id"": ""125c2f23-0c3a-4e0d-958e-96be103471b4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Atacar"",
                    ""type"": ""Button"",
                    ""id"": ""0094b103-61a5-4a88-b230-cc39ca1a2442"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Defender"",
                    ""type"": ""Button"",
                    ""id"": ""32dec6fb-53cc-4e18-b826-88b9978f5318"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interactuar"",
                    ""type"": ""Button"",
                    ""id"": ""6093b69b-29ed-4dab-91cd-51d3e42c8284"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""ASDW"",
                    ""id"": ""05ee74bf-39e6-4e3b-89b3-e1501d44856a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""da4bcf26-24f8-42f9-98a6-2f08728ce8e5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0e14464a-314c-4131-8c37-3451834937af"",
                    ""path"": ""<VirtualMouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0dee2a8d-eaae-4605-b69c-b214ecdc70d4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5a5a2463-aa7d-4e91-b898-f27707b20f0a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""139a26b9-394a-4e09-87f3-b374b9cf494e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atacar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5efcd145-f5d8-43b9-a419-2f3b79b144fd"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Defender"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46276170-f8fd-44f5-a236-e02da057924d"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interactuar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""4bcf2c8b-816d-460f-9799-e7e502be00ea"",
            ""actions"": [
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""a6aff7bb-4334-4fc1-a378-60e6cdf3be22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventario"",
                    ""type"": ""Button"",
                    ""id"": ""21d8980e-0b03-4986-9f9e-1a5a03167d31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f8e36104-9fd4-4471-ab78-924a3160f879"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0d63e19-666d-4c3a-994e-0e2864691246"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventario"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Auto"",
            ""id"": ""1175c0c8-c6ad-4809-b252-d166e6b1f68c"",
            ""actions"": [
                {
                    ""name"": ""Movimiento"",
                    ""type"": ""PassThrough"",
                    ""id"": ""12e1173f-3039-4ca5-8571-6daf40255ac1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Salir"",
                    ""type"": ""Button"",
                    ""id"": ""1ea58fb1-e1a5-4afe-9f0b-20a2c4604ab7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Turbo"",
                    ""type"": ""Button"",
                    ""id"": ""7e72d67a-6a05-4328-b56c-71d50741ffe7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""ASDW"",
                    ""id"": ""2fdb7b1f-915f-489a-a2f6-88ce8770df63"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""584abf78-ea4d-4801-9dcd-889144e4e1b3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""84460ef5-6ffe-48f3-8c8f-f74c697e5bf8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a68990d3-2a3e-4536-9fee-9b63758e7f5e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c82a48b4-5e04-4376-ae54-ef7f0cd431d9"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""721fb6c9-c631-480c-9d8c-f6af29db7135"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Salir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54e9ae9f-ac7b-4334-9101-d15b3f24bfad"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turbo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Personaje
        m_Personaje = asset.FindActionMap("Personaje", throwIfNotFound: true);
        m_Personaje_Movimiento = m_Personaje.FindAction("Movimiento", throwIfNotFound: true);
        m_Personaje_Atacar = m_Personaje.FindAction("Atacar", throwIfNotFound: true);
        m_Personaje_Defender = m_Personaje.FindAction("Defender", throwIfNotFound: true);
        m_Personaje_Interactuar = m_Personaje.FindAction("Interactuar", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Menu = m_UI.FindAction("Menu", throwIfNotFound: true);
        m_UI_Inventario = m_UI.FindAction("Inventario", throwIfNotFound: true);
        // Auto
        m_Auto = asset.FindActionMap("Auto", throwIfNotFound: true);
        m_Auto_Movimiento = m_Auto.FindAction("Movimiento", throwIfNotFound: true);
        m_Auto_Salir = m_Auto.FindAction("Salir", throwIfNotFound: true);
        m_Auto_Turbo = m_Auto.FindAction("Turbo", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Personaje
    private readonly InputActionMap m_Personaje;
    private IPersonajeActions m_PersonajeActionsCallbackInterface;
    private readonly InputAction m_Personaje_Movimiento;
    private readonly InputAction m_Personaje_Atacar;
    private readonly InputAction m_Personaje_Defender;
    private readonly InputAction m_Personaje_Interactuar;
    public struct PersonajeActions
    {
        private @Inputs m_Wrapper;
        public PersonajeActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimiento => m_Wrapper.m_Personaje_Movimiento;
        public InputAction @Atacar => m_Wrapper.m_Personaje_Atacar;
        public InputAction @Defender => m_Wrapper.m_Personaje_Defender;
        public InputAction @Interactuar => m_Wrapper.m_Personaje_Interactuar;
        public InputActionMap Get() { return m_Wrapper.m_Personaje; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PersonajeActions set) { return set.Get(); }
        public void SetCallbacks(IPersonajeActions instance)
        {
            if (m_Wrapper.m_PersonajeActionsCallbackInterface != null)
            {
                @Movimiento.started -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnMovimiento;
                @Movimiento.performed -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnMovimiento;
                @Movimiento.canceled -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnMovimiento;
                @Atacar.started -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnAtacar;
                @Atacar.performed -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnAtacar;
                @Atacar.canceled -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnAtacar;
                @Defender.started -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnDefender;
                @Defender.performed -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnDefender;
                @Defender.canceled -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnDefender;
                @Interactuar.started -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnInteractuar;
                @Interactuar.performed -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnInteractuar;
                @Interactuar.canceled -= m_Wrapper.m_PersonajeActionsCallbackInterface.OnInteractuar;
            }
            m_Wrapper.m_PersonajeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movimiento.started += instance.OnMovimiento;
                @Movimiento.performed += instance.OnMovimiento;
                @Movimiento.canceled += instance.OnMovimiento;
                @Atacar.started += instance.OnAtacar;
                @Atacar.performed += instance.OnAtacar;
                @Atacar.canceled += instance.OnAtacar;
                @Defender.started += instance.OnDefender;
                @Defender.performed += instance.OnDefender;
                @Defender.canceled += instance.OnDefender;
                @Interactuar.started += instance.OnInteractuar;
                @Interactuar.performed += instance.OnInteractuar;
                @Interactuar.canceled += instance.OnInteractuar;
            }
        }
    }
    public PersonajeActions @Personaje => new PersonajeActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Menu;
    private readonly InputAction m_UI_Inventario;
    public struct UIActions
    {
        private @Inputs m_Wrapper;
        public UIActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Menu => m_Wrapper.m_UI_Menu;
        public InputAction @Inventario => m_Wrapper.m_UI_Inventario;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Menu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMenu;
                @Inventario.started -= m_Wrapper.m_UIActionsCallbackInterface.OnInventario;
                @Inventario.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnInventario;
                @Inventario.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnInventario;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @Inventario.started += instance.OnInventario;
                @Inventario.performed += instance.OnInventario;
                @Inventario.canceled += instance.OnInventario;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // Auto
    private readonly InputActionMap m_Auto;
    private IAutoActions m_AutoActionsCallbackInterface;
    private readonly InputAction m_Auto_Movimiento;
    private readonly InputAction m_Auto_Salir;
    private readonly InputAction m_Auto_Turbo;
    public struct AutoActions
    {
        private @Inputs m_Wrapper;
        public AutoActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimiento => m_Wrapper.m_Auto_Movimiento;
        public InputAction @Salir => m_Wrapper.m_Auto_Salir;
        public InputAction @Turbo => m_Wrapper.m_Auto_Turbo;
        public InputActionMap Get() { return m_Wrapper.m_Auto; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AutoActions set) { return set.Get(); }
        public void SetCallbacks(IAutoActions instance)
        {
            if (m_Wrapper.m_AutoActionsCallbackInterface != null)
            {
                @Movimiento.started -= m_Wrapper.m_AutoActionsCallbackInterface.OnMovimiento;
                @Movimiento.performed -= m_Wrapper.m_AutoActionsCallbackInterface.OnMovimiento;
                @Movimiento.canceled -= m_Wrapper.m_AutoActionsCallbackInterface.OnMovimiento;
                @Salir.started -= m_Wrapper.m_AutoActionsCallbackInterface.OnSalir;
                @Salir.performed -= m_Wrapper.m_AutoActionsCallbackInterface.OnSalir;
                @Salir.canceled -= m_Wrapper.m_AutoActionsCallbackInterface.OnSalir;
                @Turbo.started -= m_Wrapper.m_AutoActionsCallbackInterface.OnTurbo;
                @Turbo.performed -= m_Wrapper.m_AutoActionsCallbackInterface.OnTurbo;
                @Turbo.canceled -= m_Wrapper.m_AutoActionsCallbackInterface.OnTurbo;
            }
            m_Wrapper.m_AutoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movimiento.started += instance.OnMovimiento;
                @Movimiento.performed += instance.OnMovimiento;
                @Movimiento.canceled += instance.OnMovimiento;
                @Salir.started += instance.OnSalir;
                @Salir.performed += instance.OnSalir;
                @Salir.canceled += instance.OnSalir;
                @Turbo.started += instance.OnTurbo;
                @Turbo.performed += instance.OnTurbo;
                @Turbo.canceled += instance.OnTurbo;
            }
        }
    }
    public AutoActions @Auto => new AutoActions(this);
    public interface IPersonajeActions
    {
        void OnMovimiento(InputAction.CallbackContext context);
        void OnAtacar(InputAction.CallbackContext context);
        void OnDefender(InputAction.CallbackContext context);
        void OnInteractuar(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnMenu(InputAction.CallbackContext context);
        void OnInventario(InputAction.CallbackContext context);
    }
    public interface IAutoActions
    {
        void OnMovimiento(InputAction.CallbackContext context);
        void OnSalir(InputAction.CallbackContext context);
        void OnTurbo(InputAction.CallbackContext context);
    }
}
